// <auto-generated />
namespace Final.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(s));
        
        string IMigrationMetadata.Id
        {
            get { return "201304182058524_s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
